### ISSUE TITLE
MNIST assertion error

### ISSUE THREAD

**Issue by alphamupsiomega** [ramon-oliveira/aorun#2]
```
(py3) MBP:examples $ python mnist.py
11222it [00:04, 2786.04it/s]
(60000, 28, 28) (10000, 28, 28)
Traceback (most recent call last):
  File "mnist.py", line 38, in <module>
    history = model.fit(X, y, loss=loss, val_data=(X_test, y_test))
  File "/Users/MY/Dropbox (Personal)/x/aorun/aorun/models.py", line 92, in fit
    self._build()
  File "/Users/MY/Dropbox (Personal)/x/aorun/aorun/models.py", line 33, in _build
    next_layer.build(prev_layer.output_dim)
  File "/Users/MY/Dropbox (Personal)/x/aorun/aorun/layers.py", line 57, in build
    assert type(input_dim) is int
AssertionError
```

**Comment by ramon-oliveira** [comment]
Hi @mikalyoung ,

I forgot to update the mnist  example after remove the automatic flatten behaviour, it's fixed now.

Thanks for reporting.
